/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface VicSideDrawer {
        "open": () => Promise<void>;
        "opened": boolean;
        "sdTitle": string;
    }
    interface VicStockFinder {
    }
    interface VicStockPrice {
        "stockSymbol": string;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLVicSideDrawerElement extends Components.VicSideDrawer, HTMLStencilElement {
    }
    var HTMLVicSideDrawerElement: {
        prototype: HTMLVicSideDrawerElement;
        new (): HTMLVicSideDrawerElement;
    };
    interface HTMLVicStockFinderElement extends Components.VicStockFinder, HTMLStencilElement {
    }
    var HTMLVicStockFinderElement: {
        prototype: HTMLVicStockFinderElement;
        new (): HTMLVicStockFinderElement;
    };
    interface HTMLVicStockPriceElement extends Components.VicStockPrice, HTMLStencilElement {
    }
    var HTMLVicStockPriceElement: {
        prototype: HTMLVicStockPriceElement;
        new (): HTMLVicStockPriceElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "vic-side-drawer": HTMLVicSideDrawerElement;
        "vic-stock-finder": HTMLVicStockFinderElement;
        "vic-stock-price": HTMLVicStockPriceElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface VicSideDrawer {
        "opened"?: boolean;
        "sdTitle"?: string;
    }
    interface VicStockFinder {
    }
    interface VicStockPrice {
        "stockSymbol"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "vic-side-drawer": VicSideDrawer;
        "vic-stock-finder": VicStockFinder;
        "vic-stock-price": VicStockPrice;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "vic-side-drawer": LocalJSX.VicSideDrawer & JSXBase.HTMLAttributes<HTMLVicSideDrawerElement>;
            "vic-stock-finder": LocalJSX.VicStockFinder & JSXBase.HTMLAttributes<HTMLVicStockFinderElement>;
            "vic-stock-price": LocalJSX.VicStockPrice & JSXBase.HTMLAttributes<HTMLVicStockPriceElement>;
        }
    }
}
